### ISSUE TITLE
[Bug]: Speedtest GDPR Issue

### ISSUE THREAD

**Issue by Zakary2841** [asheroto/speedtest#1]
### Checklist

- [X] I have restarted my computer to confirm this is not a transitory problem.

- [X] I have verified that I am using the latest version of speedtest.

- [X] I have verified that this issue is NOT security related (please create [security advisory](https://github.com/asheroto/speedtest/security/advisories) if so).

### What You Are Seeing?

When running as part of a non interactive script you get the following message 

==============================================================================

You may only use this Speedtest software and information generated
from it for personal, non-commercial use, through a command line
interface on a personal computer. Your use of this software is subject
to the End User License Agreement, Terms of Use and Privacy Policy at
these URLs:

	https://www.speedtest.net/about/eula
	https://www.speedtest.net/about/terms
	https://www.speedtest.net/about/privacy

==============================================================================

License acceptance recorded. Continuing.

==============================================================================

Ookla collects certain data through Speedtest that may be considered
personally identifiable, such as your IP address, unique device
identifiers or location. Ookla believes it has a legitimate interest
to share this data with internet providers, hardware manufacturers and
industry regulators to help them understand and create a better and
faster internet. For further information including how the data may be
shared, where the data may be transferred and Ookla's contact details,
please see our Privacy Policy at:

       http://www.speedtest.net/privacy

==============================================================================

To accept the message please run speedtest interactively or use the following: 

    speedtest --accept-gdpr

### System Details

Windows

**Comment by asheroto** [comment]
Hi there,

I gave the issue a presumed title. 😊

I'm guessing you are not in the USA? I didn't know that speedtest enforced GDPR but now that you bring it up, it makes sense. That message does not appear if in the USA.

I will update it now to force use of that. Thanks!

**Comment by asheroto** [comment]
Hello,

This should be fixed now, could you please confirm?

**Comment by Zakary2841** [comment]
Yeah working now thank you :) I must have missed the title area sorry for the lack of name haha!

**Comment by asheroto** [comment]
No worries. 😊 Glad it works.
